---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus
spec:
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      version: 42.3.0
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
  interval: 5m
  values:
    prometheusOperator:
      image:
        repository: quay.io/prometheus-operator/prometheus-operator
        tag: v0.52.1
      thanosImage:
        repository: quay.io/thanos/thanos
        tag: v0.25.0
      thanos:
        image:
          repository: quay.io/thanos/thanos:v0.22.0
    minio:
      image:
        repository: quay.io/minio/minio
        tag: RELEASE.2021-10-13T00-23-17Z
